"use client"

import { z } from "zod"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { Button } from "@/components/ui/button"
import {
    Form,
    FormControl,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { createCategory, createCoupon } from "@/server/user"
import { useState } from "react"
import { ChevronDownIcon, Loader2, Trash2, UploadCloudIcon } from "lucide-react"
import { toast } from "sonner"
import { useMutation, useQueryClient } from "@tanstack/react-query"
import { uploadToImageKit } from "./image-kit-upload"
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover"
import { Calendar } from "./ui/calendar"



export const formSchema = z.object({
    id: z.string().uuid().optional(), // generated by DB
    code: z.string().min(3, "Code must be at least 3 characters"),
    discountType: z.enum(["percent", "flat"]),
    discountValue: z.number().min(1, "Discount must be greater than 0"),
    isActive: z.boolean().catch(true),
    expiry: z.date().min(new Date(), "Expiry must be a future date"),
    usageLimit: z.number().min(1),
    // Backend-managed fields
    usedCount: z.number().min(0),
    createdAt: z.date().optional(),
});

export default function AddNewCouponForm() {
    const [open, setOpen] = useState(false)
    const [date, setDate] = useState<Date | undefined>(undefined)
    const [loading, setLoading] = useState(false);
    const queryClient = useQueryClient()

    const mutation = useMutation({
        mutationFn: (data: z.infer<typeof formSchema>) =>
            createCoupon({ ...data }),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["coupons"] })
            toast.success("Coupon created successfully")
            setLoading(false);
            form.reset();
        },
        onError: (error: any) => {
            toast.error(error?.message || "Something went wrong")
            setLoading(false);
        }
    })


    const form = useForm<z.infer<typeof formSchema>>({
        resolver: zodResolver(formSchema),
        defaultValues: {
            code: "",
            discountType: "percent",
            discountValue: 0,
            isActive: true,
            expiry: new Date(),
            usageLimit: 1,
            usedCount: 0,
        },
    })

    // 2. Define a submit handler.
    async function onSubmit(values: z.infer<typeof formSchema>) {
        mutation.mutate(values);
        console.log("Form values:", values);




    }
    return (
        <div className="space-y-4">
            <Form {...form} >
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
                    <FormField
                        control={form.control}
                        name="code"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>Code</FormLabel>
                                <FormControl>
                                    <Input
                                        placeholder="Code of coupon"
                                        {...field}
                                        value={field.value?.toUpperCase() || ""}
                                        onChange={(e) => field.onChange(e.target.value.toUpperCase())}
                                    />
                                </FormControl>
                                <FormMessage />
                            </FormItem>
                        )}
                    />
                    <FormField
                        control={form.control}
                        name="discountType"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>Discount Type</FormLabel>
                                <FormControl>
                                    <RadioGroup
                                        value={field.value || "percent"} // default to "percent"
                                        onValueChange={field.onChange} // already string
                                    >
                                        <div className="flex items-center space-x-2">
                                            <RadioGroupItem value="flat" id="flat" />
                                            <Label htmlFor="flat">Flat</Label>
                                        </div>
                                        <div className="flex items-center space-x-2">
                                            <RadioGroupItem value="percent" id="percent" />
                                            <Label htmlFor="percent">Percent</Label>
                                        </div>
                                    </RadioGroup>
                                </FormControl>
                                <FormMessage />
                            </FormItem>
                        )}
                    />
                    <FormField
                        control={form.control}
                        name="discountValue"
                        render={({ field }) => {
                            const discountType = form.watch("discountType"); // ✅ declare outside JSX

                            return (
                                <FormItem>
                                    <FormLabel>Discount Value</FormLabel>
                                    <FormControl>
                                        <div className="relative">
                                            <Input
                                                placeholder="Value of discount"
                                                {...field}
                                                value={field.value || ""}
                                                onChange={(e) => field.onChange(Number(e.target.value))}
                                                className="pr-10"
                                                type="number" // forces numeric input
                                            />
                                            <span className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500">
                                                {discountType === "percent" ? "%" : "₹"}
                                            </span>
                                        </div>
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                            );
                        }}
                    />
                    <FormField
                        control={form.control}
                        name="isActive"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>Is Active</FormLabel>
                                <FormControl>
                                    <RadioGroup
                                        value={field.value ? "true" : "false"} // boolean -> string
                                        onValueChange={(val) => field.onChange(val === "true")} // string -> boolean
                                    >
                                        <div className="flex items-center space-x-2">
                                            <RadioGroupItem value="true" id="true" />
                                            <Label htmlFor="true">True</Label>
                                        </div>
                                        <div className="flex items-center space-x-2">
                                            <RadioGroupItem value="false" id="false" />
                                            <Label htmlFor="false">False</Label>
                                        </div>
                                    </RadioGroup>
                                </FormControl>

                                <FormMessage />
                            </FormItem>
                        )}
                    />
                    <FormField
                        control={form.control}
                        name="expiry"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>Expiry</FormLabel>
                                <FormControl>
                                    <div className="flex flex-col gap-3">


                                        <Popover>
                                            <PopoverTrigger asChild>
                                                <Button
                                                    variant="outline"
                                                    id="date"
                                                    className="w-48 justify-between font-normal"
                                                >
                                                    {field.value
                                                        ? new Date(field.value).toLocaleDateString()
                                                        : "Select date"}
                                                    <ChevronDownIcon />
                                                </Button>
                                            </PopoverTrigger>

                                            <PopoverContent
                                                className="w-auto overflow-hidden p-0"
                                                align="start"
                                            >
                                                <Calendar
                                                    mode="single"
                                                    selected={field.value ? new Date(field.value) : undefined}
                                                    captionLayout="dropdown"
                                                    onSelect={(date) => {
                                                        field.onChange(date); // ✅ update form state
                                                        setOpen(false);
                                                    }}
                                                />
                                            </PopoverContent>
                                        </Popover>
                                    </div>
                                </FormControl>

                                <FormMessage />
                            </FormItem>
                        )}
                    />
                    <FormField
                        control={form.control}
                        name="usageLimit"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>No of times you want this coupon to be used</FormLabel>
                                <FormControl>
                                     <Input
                                        placeholder="Usage limit"
                                        {...field}
                                        value={field.value || ""}
                                        onChange={(e) => field.onChange(Number(e.target.value))}
                                        className="pr-10"
                                        type="number" // forces numeric input
                                    />
                                </FormControl>

                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    <FormField
                        control={form.control}
                        name="usedCount"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>How many times this coupon has been used</FormLabel>
                                <FormControl>
                                    <Input placeholder="Usage limit" {...field} readOnly />
                                </FormControl>

                                <FormMessage />
                            </FormItem>
                        )}
                    />

                    <Button type="submit" disabled={mutation.isPending}>
                        {mutation.isPending ? (
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                            "Submit"
                        )}
                    </Button>
                </form>
            </Form>
        </div>
    )
}
