import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner"
import { SiteHeader } from "@/components/site-header"
import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"
import Providers from "../(dashboard)/admin/provider/tanstack"
import { AppSidebarNew } from "@/components/ui/app-sidebar-new";
import BottomNav from "@/components/ui/bottom-navigation";
import ClientMuiProvider from "@/components/client-mui-provider";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <meta name="viewport" content="initial-scale=1, width=device-width" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground font-sans`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>

            <ClientMuiProvider>
              <div className=" mx-auto max-w-[1920px]">
                {/* TanStack Query Provider */}
                <SidebarProvider defaultOpen={false}
                  style={
                    {
                      "--sidebar-width": "calc(var(--spacing) * 72)",
                      "--header-height": "calc(var(--spacing) * 20)",
                    } as React.CSSProperties
                  }
                >
                  <div className="block md:hidden" >
                    <AppSidebarNew />
                  </div>
                  {/* Main Layout contain Header and Page */}
                  <SidebarInset className="text-foreground">
                    <div className="flex flex-col h-[100dvh] overflow-hidden">
                      <SiteHeader />

                    {/* It is main content area */}

                      <div className="flex-1 border mb-16 md:mb-0 bg-white dark:bg-background-header overflow-auto pb-14 md:pb-0">
                        {children}
                      </div>

                      <Toaster richColors />
                    </div>
                  </SidebarInset>

                  {/* Bottom navigation appeared in Mobile View */}
                  <BottomNav />
                </SidebarProvider>
              </div>
            </ClientMuiProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
